package com.upiiz.platform_api.models;

public enum NotificationType {
    INVITE, RESCHEDULED, CANCELLED, REMINDER, FORUM_REPLY, FORUM_LIKE, FORUM_REPORTED, FORUM_REPORT_RESOLVED,
    NEW_MESSAGE,
    MESSAGE_REPORT_SENT,
    MESSAGE_REPORTED_ADMIN
}
