version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-tt
    restart: always
    environment:
      POSTGRES_DB: upiiz_platform
      POSTGRES_USER: upiiz
      POSTGRES_PASSWORD: upiiz123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tt-network

  backend:
    build: .
    container_name: backend-tt
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ttupiiz-postgrestt-448d32:5432/upiiz_platform
      SPRING_DATASOURCE_USERNAME: upiiz
      SPRING_DATASOURCE_PASSWORD: upiiz123

      JWT_SECRET: PSECe1ioyABW1HE5E1uLqKRVPUcv2KKmsqmJ4jGmQ/Esau+HM1KESqvFCinolgxZ3xu1NTJorfc79151HVHbtw==
      TOKEN: 2001657889653220
      MAIL_USER: upiiz.notificaciones@gmail.com
      MAIL_PASS: czdr wxcv zdph smqe

      APP_FRONTEND_URL: https://app.kalypi.xyz
      SPRING_PROFILES_ACTIVE: prod

    ports:
      - "8080:8080"
    networks:
      - tt-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-tt
    restart: always
    ports:
      - "80:80"
    networks:
      - tt-network

volumes:
  postgres_data:

networks:
  tt-network:
    driver: bridge
