server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: upiiz.notificaciones@gmail.com
    password: czdr wxcv zdph smqe
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  datasource:
    url: jdbc:postgresql://148.204.142.20:5432/upiiz_platform
    username: upiiz
    password: upiizpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    jwt:
      issuer: upiiz-platform
      access-exp-min: 15
      refresh-exp-days: 14
      secret: PSECe1ioyABWlHE5E1uLqKRVPUcv2KKmsqmJ4jGmQ/Esau+HMlKESqvFCinolgxZ3xu1NTJorfc79I51HVHbtw==
  gesco:
    enabled: true
    base-url: "http://148.204.142.2/pump/web/index.php/login"
    token: 2001657889653220
    timeout-ms: 5000

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

chat:
  storage:
    baseDir: ./data/chat-uploads
    maxBytes: 15728640
